const { Command } = require('discord-akairo');
const { MessageEmbed } = require('discord.js');
const axios = require('axios');

class InspiroBotCommand extends Command {
    constructor() {
        super('ib', {
            aliases: ['ib', 'inspirobot'],
            category: 'general',
            clientPermissions: ["SEND_MESSAGES" ,'EMBED_LINKS'],
            description: {
                content: 'Returns an inspirational image generated by inspirobot',
                usage: '[]',
                examples: ['']
            }
        });
    }

    async exec(message) {

        const embed = new MessageEmbed()
            .setAuthor(message.member.user.tag, message.member.user.displayAvatarURL())
            .setColor(message.member ? message.member.displayHexColor : 'RANDOM')
            .setTitle('InspiroBot')
            .setFooter('Powered by https://inspirobot.me/')

        await axios.get('http://inspirobot.me/api?generate=true')
        .then(async (response) => {

            const result = response.data;

            embed.setImage(result)
            .setURL(result);
        

            await message.channel.send(embed);

        })

    }
}

module.exports = InspiroBotCommand;